using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace OttoMapper.Generator
{
    /// <summary>
    /// Emits the source text for generated map classes and the registry aggregator.
    /// Pure string emission: no symbol access beyond what the classifier already captured.
    /// </summary>
    internal static class Emitter
    {
        private const string MapNamespace = "OttoMapper.Generated";
        private const string RegistryFqdn = "global::OttoMapper.Mapping.Generated.GeneratedMapRegistry";
        private const string MapRuntimeFqdn = "global::OttoMapper.Mapping.Generated.MapRuntime";

        /// <summary>
        /// Emits all generated source files. Returns (hintName, source) pairs.
        /// </summary>
        public static IEnumerable<(string HintName, string Source)> Emit(ClassificationResult result)
        {
            foreach (var pair in result.Generated)
            {
                yield return ($"{MapNamespace}.{Naming.MapClassName(pair.Pair.Source, pair.Pair.Destination)}.g.cs", EmitMapClass(pair));
            }

            if (result.Generated.Count > 0)
            {
                yield return ($"{MapNamespace}.GeneratedMaps.g.cs", EmitAggregator(result.Generated));
            }
        }

        /// <summary>
        /// Emits diagnostics for skipped pairs.
        /// </summary>
        public static IEnumerable<(Location Location, Diagnostic Diagnostic)> EmitDiagnostics(ClassificationResult result)
        {
            foreach (var skipped in result.Skipped)
            {
                yield return (skipped.Pair.Declaration.Location, Diagnostic.Create(
                    DiagnosticDescriptors.PairFallsBackToRuntime,
                    skipped.Pair.Declaration.Location,
                    skipped.Pair.Source.ToDisplayString(),
                    skipped.Pair.Destination.ToDisplayString(),
                    skipped.Reason));
            }
        }

        private static string EmitMapClass(GeneratedPair pair)
        {
            var src = pair.Pair.Source;
            var dst = pair.Pair.Destination;
            var className = Naming.MapClassName(src, dst);
            var srcFq = Naming.FullyQualified(src);
            var dstFq = Naming.FullyQualified(dst);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {MapNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    internal static partial class {className}");
            sb.AppendLine("    {");
            sb.Append($"        public static {dstFq} Map({srcFq} src)");

            // Emit the body, with a top-level null guard when the source type can be null.
            if (SymbolHelpers.CanBeNull(src))
            {
                sb.AppendLine();
                sb.AppendLine("        {");
                sb.AppendLine("            if (src is null) return default!;");
            }
            else
            {
                sb.AppendLine();
                sb.AppendLine("        {");
            }

            sb.AppendLine($"            var dest = new {dstFq}();");

            foreach (var member in pair.Members)
            {
                EmitMember(sb, member);
            }

            sb.AppendLine("            return dest;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitMember(StringBuilder sb, MemberPlan member)
        {
            var destName = member.DestProp.Name;
            var srcName = member.SourceProp!.Name;
            var srcAccess = $"src.{srcName}";
            var dstPropType = member.DestProp.Type;
            var srcPropType = member.SourceProp.Type;

            switch (member.Kind)
            {
                case MemberKind.DirectAssign:
                    sb.AppendLine($"            dest.{destName} = {srcAccess};");
                    break;

                case MemberKind.Convert:
                    sb.AppendLine($"            dest.{destName} = {MapRuntimeFqdn}.Convert<{Naming.FullyQualified(srcPropType)}, {Naming.FullyQualified(dstPropType)}>({srcAccess});");
                    break;

                case MemberKind.CollectionSame when member.CollectionKind == SymbolHelpers.CollectionTarget.Direct:
                    sb.AppendLine($"            dest.{destName} = {srcAccess};");
                    break;

                case MemberKind.CollectionSame:
                    {
                        var elem = Naming.FullyQualified(member.SrcElem!);
                        var mapper = "x => x";
                        sb.AppendLine($"            dest.{destName} = {Materialize(member.CollectionKind, member.DstElem!, dstPropType, elem, elem, mapper, srcAccess)};");
                        break;
                    }

                case MemberKind.CollectionConvert:
                    {
                        var se = Naming.FullyQualified(member.SrcElem!);
                        var de = Naming.FullyQualified(member.DstElem!);
                        var mapper = $"x => {MapRuntimeFqdn}.Convert<{se}, {de}>(x)";
                        sb.AppendLine($"            dest.{destName} = {Materialize(member.CollectionKind, member.DstElem!, dstPropType, se, de, mapper, srcAccess)};");
                        break;
                    }

                case MemberKind.CollectionNested:
                    {
                        var se = Naming.FullyQualified(member.SrcElem!);
                        var de = Naming.FullyQualified(member.DstElem!);
                        var sibling = $"{MapNamespace}.{Naming.MapClassName(member.NestedSource!, member.NestedDest!)}.Map";
                        var mapper = $"x => {sibling}(x)";
                        sb.AppendLine($"            dest.{destName} = {Materialize(member.CollectionKind, member.DstElem!, dstPropType, se, de, mapper, srcAccess)};");
                        break;
                    }

                case MemberKind.Nested:
                    {
                        var sibling = $"{MapNamespace}.{Naming.MapClassName(member.NestedSource!, member.NestedDest!)}.Map";
                        if (SymbolHelpers.CanBeNull(srcPropType))
                        {
                            var nestedDstFq = Naming.FullyQualified(member.NestedDest!);
                            sb.AppendLine($"            dest.{destName} = {srcAccess} is null ? default({nestedDstFq}) : {sibling}({srcAccess});");
                        }
                        else
                        {
                            sb.AppendLine($"            dest.{destName} = {sibling}({srcAccess});");
                        }
                        break;
                    }
            }
        }

        private static string Materialize(SymbolHelpers.CollectionTarget target, ITypeSymbol dstElem, ITypeSymbol dstPropType, string srcElemFq, string dstElemFq, string mapper, string srcAccess)
        {
            switch (target)
            {
                case SymbolHelpers.CollectionTarget.Array:
                    return $"{MapRuntimeFqdn}.MapToArray<{srcElemFq}, {dstElemFq}>({srcAccess}, {mapper})";

                case SymbolHelpers.CollectionTarget.List:
                    return $"{MapRuntimeFqdn}.MapToList<{srcElemFq}, {dstElemFq}>({srcAccess}, {mapper})";

                case SymbolHelpers.CollectionTarget.Ctor:
                    {
                        var dstPropFq = Naming.FullyQualified(dstPropType);
                        return $"new {dstPropFq}({MapRuntimeFqdn}.MapToList<{srcElemFq}, {dstElemFq}>({srcAccess}, {mapper}))";
                    }

                default:
                    return $"{MapRuntimeFqdn}.MapToList<{srcElemFq}, {dstElemFq}>({srcAccess}, {mapper})";
            }
        }

        private static string EmitAggregator(List<GeneratedPair> generated)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {MapNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class GeneratedMaps");
            sb.AppendLine("    {");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");

            foreach (var pair in generated)
            {
                var srcFq = Naming.FullyQualified(pair.Pair.Source);
                var dstFq = Naming.FullyQualified(pair.Pair.Destination);
                var mapClass = Naming.MapClassName(pair.Pair.Source, pair.Pair.Destination);
                sb.AppendLine($"            {RegistryFqdn}.RegisterObject<{srcFq}, {dstFq}>(");
                sb.AppendLine($"                new global::System.Func<{srcFq}, {dstFq}>(OttoMapper.Generated.{mapClass}.Map),");
                sb.AppendLine($"                new global::System.Func<object, object>(__o => OttoMapper.Generated.{mapClass}.Map(({srcFq})__o!)));");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}